// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ``` email, password, phone number,
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI-eWBa14Z3jrOaY_Y6A-lsmfoL7z4D9c',
    appId: '1:863516411610:web:2e87b1120e703e011a87e3',
    messagingSenderId: '863516411610',
    projectId: 'yanafssi',
    authDomain: 'yanafssi.firebaseapp.com',
    storageBucket: 'yanafssi.firebasestorage.app',
    measurementId: 'G-F1Z88B0873',
    databaseURL:
        'https://yanafssi-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5KHM24xcWss0r1Fo4o1LIWwHvLnjsjXo',
    appId: '1:863516411610:android:13514d3b564aaf301a87e3',
    messagingSenderId: '863516411610',
    projectId: 'yanafssi',
    storageBucket: 'yanafssi.firebasestorage.app',
    databaseURL:
        'https://yanafssi-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvvI5tZePEXztL82CbjNbFKu03Y9Tdsas',
    appId: '1:863516411610:ios:98d87100bbe43c331a87e3',
    messagingSenderId: '863516411610',
    projectId: 'yanafssi',
    storageBucket: 'yanafssi.firebasestorage.app',
    iosBundleId: 'com.example.client',
    databaseURL:
        'https://yanafssi-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvvI5tZePEXztL82CbjNbFKu03Y9Tdsas',
    appId: '1:863516411610:ios:98d87100bbe43c331a87e3',
    messagingSenderId: '863516411610',
    projectId: 'yanafssi',
    storageBucket: 'yanafssi.firebasestorage.app',
    iosBundleId: 'com.example.client',
    databaseURL:
        'https://yanafssi-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI-eWBa14Z3jrOaY_Y6A-lsmfoL7z4D9c',
    appId: '1:863516411610:web:1e7ee693991dab921a87e3',
    messagingSenderId: '863516411610',
    projectId: 'yanafssi',
    authDomain: 'yanafssi.firebaseapp.com',
    storageBucket: 'yanafssi.firebasestorage.app',
    measurementId: 'G-4CENJPMQJW',
    databaseURL:
        'https://yanafssi-default-rtdb.europe-west1.firebasedatabase.app',
  );
}
