import 'package:flutter/material.dart';

class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  Locale _currentLocale = const Locale('en');
  Locale get currentLocale => _currentLocale;

  void changeLocale(String languageCode) {
    _currentLocale = Locale(languageCode);
    notifyListeners();
  }

  String? _selectedCountry;
  String? get selectedCountry => _selectedCountry;

  void setCountry(String country) {
    _selectedCountry = country;
    notifyListeners();
  }

  String translate(String key) {
    if (_currentLocale.languageCode == 'ar' && _selectedCountry != null) {
      if (_dialectValues.containsKey(_selectedCountry) &&
          _dialectValues[_selectedCountry]!.containsKey(key)) {
        return _dialectValues[_selectedCountry]![key]!;
      }
    }
    return _localizedValues[_currentLocale.languageCode]?[key] ?? key;
  }

  static final Map<String, Map<String, String>> _dialectValues = {
    'Algeria': {
      'q1': 'شحال من خطرة تجي في بالك تكونسومي؟',
      'q2': 'اسكو الكونسوماسيون تاعك راهي تخلطلك حياتك اليومية؟',
      'q3': 'سييت تحبس من قبل وما قدرتش؟',
      'q4': 'تحس روحك مقلق كي ما تكونسوميش؟',
    },
    'Egypt': {
      'q1': 'بتحس كام مرة إنك عايز تضرب؟',
      'q2': 'هل الشرب مأثر على حياتك ومسؤولياتك؟',
      'q3': 'حاولت تبطل قبل كده وفشلت؟',
      'q4': 'بتحس بقلق لو مش عارف تضرب؟',
    },
    'Saudi Arabia': {
      'q1': 'كم مرة تحس إنك تبي تتعاطى؟',
      'q2': 'هل تعاطيك مأثر على حياتك اليومية؟',
      'q3': 'جربت توقف من قبل وما قدرت؟',
      'q4': 'تحس بتوتر لو ما تعاطيت؟',
    },
  };

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'YaNafssi',
      'tagline': 'Recovery & Support Together',
      'im_hooked': "I'm Hooked",
      'start_recovery': 'Start Recovery',
      'i_want_to_help': 'I Want to Help',
      'offer_support': 'Offer Support',
      'help_me': 'Help Me',
      'analyze_danger': 'Analyze Danger & Risks',
      'how_feel': 'How do you feel\ntoday?',
      'select_mood': 'Select the emoji that best represents your current mood.',
      'mood_sad': 'Sad',
      'mood_angry': 'Angry',
      'mood_anxious': 'Anxious',
      'mood_neutral': 'Neutral',
      'mood_okay': 'Okay',
      'mood_tired': 'Tired',
      'mood_overwhelmed': 'Overwhelmed',
      'mood_lonely': 'Lonely',
      'mood_hurt': 'Hurt',
      'support_chat': 'Support Chat',
      'assessment': 'Assessment',
      'talk_listening': "Talk, I'm listening\nto you right now",
      'type_message': 'Type your message...',
      'chat_intro':
          "Hello. I'm here for you. You can tell me anything—I'm listening.",
      'chat_error':
          "I'm having trouble connecting right now, but I'm still here with you.",
      'assessment_complete': 'Assessment Complete',
      'assessment_result_prefix': 'Based on your answers, your status is:',
      'low_dependency': 'Low Dependency',
      'medium_dependency': 'Medium Dependency',
      'high_dependency': 'High Dependency',
      'finish': 'Finish',
      'question_progress': 'Question',
      'never': 'Never',
      'sometimes': 'Sometimes',
      'often': 'Often',
      'always': 'Always',
      'support_others': 'Support Others',
      'join_community': 'Join our community of helpers',
      'fill_details': 'Please fill in your details to get verified.',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'wilaya': 'Wilaya',
      'commune': 'Commune',
      'identity_verification': 'Identity Verification',
      'id_front': 'ID Front',
      'id_back': 'ID Back',
      'take_selfie': 'Take a Selfie',
      'submit_application': 'Submit Application',
      'upload_required': 'Please upload all required images',
      'success_submit': 'Application Submitted Successfully!',
      'failed_upload': 'Failed to upload images',
      'risk_analysis': 'Risk Analysis',
      'describe_situation': 'Describe the Situation',
      'enter_details_hint':
          'Enter details about the person, effects, or upload a photo of the substance/situation.',
      'text_hint': 'E.g., "My friend took a blue pill and is feeling dizzy..."',
      'take_photo': 'Take Photo',
      'upload': 'Upload',
      'analyze_btn': 'Analyze Danger',
      'analysis_result': 'Analysis Result',
      'error_analyzing': 'Error analyzing situation. Please try again.',
      'please_provide_input': 'Please provide text or an image.',
      'q1': 'How often do you feel the urge to use?',
      'q2': 'Does your usage affect your daily responsibilities?',
      'q3': 'Have you tried to stop before but failed?',
      'q4': 'Do you feel anxious when you cannot use?',
      'please_enter': 'Please enter',
      'yes': 'Yes',
      'no': 'No',
      'type_answer': 'Type your answer here...',
      'choose_support': 'Choose Support',
      'choose_support_desc':
          'Select how you would like to receive support today.',
      'chat_support': 'Chat Support',
      'chat_with_ai': 'Chat with our AI Assistant',
      'live_rooms': 'Live Rooms',
      'join_group_sessions': 'Join live group sessions',
      'support_rooms': 'Support Rooms',
      'join_conversation': 'Join the conversation',
      'join_now': 'Join Now',
      'select_country': 'Select your Country',
      'choose_region': 'Choose your region for a better experience',
      'preparing_assessment': 'Preparing your assessment...',
      'request_submitted': 'Request Submitted',
      'wait_admin_approval':
          'Please wait until the admin accepts your request.',
      'ok': 'OK',
      'specialty': 'Specialty',
      'license_certificate': 'License/Certificate',
      'specialist_dashboard': 'Specialist Dashboard',
      'welcome_specialist': 'Welcome, Specialist!',
      'start_helping': 'You can now start helping others.',
      'live': 'LIVE',
      'upcoming': 'UPCOMING',
      'by': 'by',
      'please_select_specialty': 'Please select a specialty',
      'psychologist': 'Psychologist',
      'deen_helper': 'Deen Helper',
      'sports_coach': 'Sports Coach',
      'nutrition_specialist': 'Nutrition Specialist',
      'other': 'Other',
      'anxiety_support_group': 'Anxiety Support Group',
      'mindfulness_session': 'Mindfulness Session',
      'addiction_recovery': 'Addiction Recovery',
      'evening_meditation': 'Evening Meditation',
      'open_talk': 'Open Talk',
      'dr_sarah': 'Dr. Sarah',
      'coach_mike': 'Coach Mike',
      'specialist_amine': 'Specialist Amine',
      'dr_lina': 'Dr. Lina',
      'community': 'Community',
      'algeria': 'Algeria',
      'egypt': 'Egypt',
      'saudi_arabia': 'Saudi Arabia',
      'united_states': 'United States',
      'france': 'France',
      'rooms': 'Rooms',
      'gifts': 'Gifts',
      'profile': 'Profile',
      'my_rooms': 'My Rooms',
      'now': 'Now',
      'reserved': 'Reserved',
      'create_room': 'Create Room',
      'no_rooms_found': 'No rooms found',
      'participants': 'Participants',
      'active': 'Active',
      'pending': 'Pending',
      'create': 'Create',
      'room_title': 'Room Title',
      'enter_room_title': 'Enter room title',
      'room_type': 'Room Type',
      'no_active_rooms': 'No active rooms found',
      'profile_details': 'Profile Details',
      'coming_soon': 'Coming Soon',
    },
    'fr': {
      'app_name': 'YaNafssi',
      'tagline': 'Rétablissement et soutien ensemble',
      'im_hooked': "Je suis accro",
      'start_recovery': 'Commencer le rétablissement',
      'i_want_to_help': 'Je veux aider',
      'offer_support': 'Offrir du soutien',
      'help_me': 'Aidez-moi',
      'analyze_danger': 'Analyser les dangers et risques',
      'how_feel': 'Comment vous sentez-vous\naujourd\'hui ?',
      'select_mood':
          'Sélectionnez l\'emoji qui représente le mieux votre humeur actuelle.',
      'mood_sad': 'Triste',
      'mood_angry': 'En colère',
      'mood_anxious': 'Anxieux',
      'mood_neutral': 'Neutre',
      'mood_okay': 'Ça va',
      'mood_tired': 'Fatigué',
      'mood_overwhelmed': 'Débordé',
      'mood_lonely': 'Seul',
      'mood_hurt': 'Blessé',
      'support_chat': 'Chat de soutien',
      'assessment': 'Évaluation',
      'talk_listening': "Parlez, je vous écoute\nen ce moment",
      'type_message': 'Tapez votre message...',
      'chat_intro':
          "Bonjour. Je suis là pour vous. Vous pouvez tout me dire, je vous écoute.",
      'chat_error':
          "J'ai du mal à me connecter pour le moment, mais je suis toujours là avec vous.",
      'assessment_complete': 'Évaluation terminée',
      'assessment_result_prefix': 'Selon vos réponses, votre statut est :',
      'low_dependency': 'Faible dépendance',
      'medium_dependency': 'Dépendance moyenne',
      'high_dependency': 'Forte dépendance',
      'finish': 'Terminer',
      'question_progress': 'Question',
      'never': 'Jamais',
      'sometimes': 'Parfois',
      'often': 'Souvent',
      'always': 'Toujours',
      'support_others': 'Soutenir les autres',
      'join_community': 'Rejoignez notre communauté d\'aidants',
      'fill_details': 'Veuillez remplir vos coordonnées pour être vérifié.',
      'full_name': 'Nom complet',
      'phone_number': 'Numéro de téléphone',
      'wilaya': 'Wilaya',
      'commune': 'Commune',
      'identity_verification': 'Vérification d\'identité',
      'id_front': 'Recto ID',
      'id_back': 'Verso ID',
      'take_selfie': 'Prendre un selfie',
      'submit_application': 'Soumettre la demande',
      'upload_required': 'Veuillez télécharger toutes les images requises',
      'success_submit': 'Demande soumise avec succès !',
      'failed_upload': 'Échec du téléchargement des images',
      'risk_analysis': 'Analyse des risques',
      'describe_situation': 'Décrivez la situation',
      'enter_details_hint':
          'Entrez des détails sur la personne, les effets, ou téléchargez une photo de la substance/situation.',
      'text_hint':
          'Ex : "Mon ami a pris une pilule bleue et se sent étourdi..."',
      'take_photo': 'Prendre une photo',
      'upload': 'Télécharger',
      'analyze_btn': 'Analyser le danger',
      'analysis_result': 'Résultat de l\'analyse',
      'error_analyzing':
          'Erreur lors de l\'analyse de la situation. Veuillez réessayer.',
      'please_provide_input': 'Veuillez fournir du texte ou une image.',
      'q1': 'À quelle fréquence ressentez-vous l\'envie de consommer ?',
      'q2':
          'Votre consommation affecte-t-elle vos responsabilités quotidiennes ?',
      'q3': 'Avez-vous déjà essayé d\'arrêter sans succès ?',
      'q4': 'Vous sentez-vous anxieux lorsque vous ne pouvez pas consommer ?',
      'please_enter': 'Veuillez entrer',
      'yes': 'Oui',
      'no': 'Non',
      'type_answer': 'Tapez votre réponse ici...',
      'choose_support': 'Choisir le soutien',
      'choose_support_desc':
          'Sélectionnez comment vous souhaitez recevoir du soutien aujourd\'hui.',
      'chat_support': 'Chat de soutien',
      'chat_with_ai': 'Discutez avec notre assistant IA',
      'live_rooms': 'Salons en direct',
      'join_group_sessions': 'Rejoignez des sessions de groupe en direct',
      'support_rooms': 'Salons de soutien',
      'join_conversation': 'Rejoindre la conversation',
      'join_now': 'Rejoindre maintenant',
      'select_country': 'Sélectionnez votre pays',
      'choose_region': 'Choisissez votre région pour une meilleure expérience',
      'preparing_assessment': 'Préparation de votre évaluation...',
      'request_submitted': 'Demande soumise',
      'wait_admin_approval':
          'Veuillez attendre que l\'administrateur accepte votre demande.',
      'ok': 'OK',
      'specialty': 'Spécialité',
      'license_certificate': 'Licence/Certificat',
      'specialist_dashboard': 'Tableau de bord spécialiste',
      'welcome_specialist': 'Bienvenue, Spécialiste !',
      'start_helping': 'Vous pouvez maintenant commencer à aider les autres.',
      'live': 'EN DIRECT',
      'upcoming': 'À VENIR',
      'by': 'par',
      'please_select_specialty': 'Veuillez sélectionner une spécialité',
      'psychologist': 'Psychologue',
      'deen_helper': 'Aide religieuse',
      'sports_coach': 'Coach sportif',
      'nutrition_specialist': 'Nutritionniste',
      'other': 'Autre',
      'anxiety_support_group': 'Groupe de soutien anxiété',
      'mindfulness_session': 'Séance de pleine conscience',
      'addiction_recovery': 'Rétablissement de l\'addiction',
      'evening_meditation': 'Méditation du soir',
      'open_talk': 'Discussion ouverte',
      'dr_sarah': 'Dr. Sarah',
      'coach_mike': 'Coach Mike',
      'specialist_amine': 'Spécialiste Amine',
      'dr_lina': 'Dr. Lina',
      'community': 'Communauté',
      'algeria': 'Algérie',
      'egypt': 'Égypte',
      'saudi_arabia': 'Arabie Saoudite',
      'united_states': 'États-Unis',
      'france': 'France',
      'rooms': 'Salons',
      'gifts': 'Cadeaux',
      'profile': 'Profil',
      'my_rooms': 'Mes Salons',
      'now': 'Maintenant',
      'reserved': 'Réservé',
      'create_room': 'Créer un salon',
      'no_rooms_found': 'Aucun salon trouvé',
      'participants': 'Participants',
      'active': 'Actif',
      'pending': 'En attente',
      'create': 'Créer',
      'room_title': 'Titre du salon',
      'enter_room_title': 'Entrez le titre du salon',
      'room_type': 'Type de salon',
      'no_active_rooms': 'Aucun salon actif trouvé',
      'profile_details': 'Détails du profil',
      'coming_soon': 'Bientôt disponible',
    },
    'ar': {
      'app_name': 'يانفسي',
      'tagline': 'التعافي والدعم معًا',
      'im_hooked': "أنا مدمن",
      'start_recovery': 'ابدأ التعافي',
      'i_want_to_help': 'أريد المساعدة',
      'offer_support': 'تقديم الدعم',
      'help_me': 'ساعدني',
      'analyze_danger': 'تحليل الخطر والمخاطر',
      'how_feel': 'كيف تشعر\nاليوم؟',
      'select_mood': 'اختر الرمز التعبيري الذي يمثل حالتك المزاجية الحالية.',
      'mood_sad': 'حزين',
      'mood_angry': 'غاضب',
      'mood_anxious': 'قلق',
      'mood_neutral': 'محايد',
      'mood_okay': 'بخير',
      'mood_tired': 'متعب',
      'mood_overwhelmed': 'مضغوط',
      'mood_lonely': 'وحيد',
      'mood_hurt': 'مجروح',
      'support_chat': 'دردشة الدعم',
      'assessment': 'التقييم',
      'talk_listening': "تحدث، أنا أستمع\nإليك الآن",
      'type_message': 'اكتب رسالتك...',
      'chat_intro':
          "مرحبًا. أنا هنا من أجلك. يمكنك إخباري بأي شيء - أنا أستمع.",
      'chat_error': "أواجه مشكلة في الاتصال الآن، لكنني ما زلت هنا معك.",
      'assessment_complete': 'اكتمل التقييم',
      'assessment_result_prefix': 'بناءً على إجاباتك، حالتك هي:',
      'low_dependency': 'تبعية منخفضة',
      'medium_dependency': 'تبعية متوسطة',
      'high_dependency': 'تبعية عالية',
      'finish': 'إنهاء',
      'question_progress': 'سؤال',
      'never': 'أبداً',
      'sometimes': 'أحياناً',
      'often': 'غالباً',
      'always': 'دائماً',
      'support_others': 'دعم الآخرين',
      'join_community': 'انضم إلى مجتمع المساعدين لدينا',
      'fill_details': 'يرجى ملء بياناتك للتحقق.',
      'full_name': 'الاسم الكامل',
      'phone_number': 'رقم الهاتف',
      'wilaya': 'الولاية',
      'commune': 'البلدية',
      'identity_verification': 'التحقق من الهوية',
      'id_front': 'صورة الهوية (أمام)',
      'id_back': 'صورة الهوية (خلف)',
      'take_selfie': 'التقاط صورة سيلفي',
      'submit_application': 'تقديم الطلب',
      'upload_required': 'يرجى تحميل جميع الصور المطلوبة',
      'success_submit': 'تم تقديم الطلب بنجاح!',
      'failed_upload': 'فشل تحميل الصور',
      'risk_analysis': 'تحليل المخاطر',
      'describe_situation': 'صف الموقف',
      'enter_details_hint':
          'أدخل تفاصيل حول الشخص، التأثيرات، أو قم بتحميل صورة للمادة/الموقف.',
      'text_hint': 'مثال: "صديقي أخذ حبة زرقاء ويشعر بالدوار..."',
      'take_photo': 'التقاط صورة',
      'upload': 'تحميل',
      'analyze_btn': 'تحليل الخطر',
      'analysis_result': 'نتيجة التحليل',
      'error_analyzing': 'خطأ في تحليل الموقف. يرجى المحاولة مرة أخرى.',
      'please_provide_input': 'يرجى تقديم نص أو صورة.',
      'q1': 'كم مرة تشعر بالرغبة في التعاطي؟',
      'q2': 'هل يؤثر تعاطيك على مسؤولياتك اليومية؟',
      'q3': 'هل حاولت التوقف من قبل وفشلت؟',
      'q4': 'هل تشعر بالقلق عندما لا تستطيع التعاطي؟',
      'please_enter': 'الرجاء إدخال',
      'yes': 'نعم',
      'no': 'لا',
      'type_answer': 'اكتب إجابتك هنا...',
      'choose_support': 'اختر الدعم',
      'choose_support_desc': 'اختر كيف تود تلقي الدعم اليوم.',
      'chat_support': 'دردشة الدعم',
      'chat_with_ai': 'تحدث مع مساعدنا الذكي',
      'live_rooms': 'غرف مباشرة',
      'join_group_sessions': 'انضم إلى جلسات جماعية مباشرة',
      'support_rooms': 'غرف الدعم',
      'join_conversation': 'انضم للمحادثة',
      'join_now': 'انضم الآن',
      'select_country': 'اختر بلدك',
      'choose_region': 'اختر منطقتك لتجربة أفضل',
      'preparing_assessment': 'جاري إعداد التقييم...',
      'request_submitted': 'تم تقديم الطلب',
      'wait_admin_approval': 'يرجى الانتظار حتى يوافق المسؤول على طلبك.',
      'ok': 'حسناً',
      'specialty': 'التخصص',
      'license_certificate': 'الرخصة/الشهادة',
      'specialist_dashboard': 'لوحة تحكم الأخصائي',
      'welcome_specialist': 'مرحباً أيها الأخصائي!',
      'start_helping': 'يمكنك الآن البدء في مساعدة الآخرين.',
      'live': 'مباشر',
      'upcoming': 'قادم',
      'by': 'بواسطة',
      'please_select_specialty': 'يرجى اختيار التخصص',
      'psychologist': 'طبيب نفساني',
      'deen_helper': 'مساعد ديني',
      'sports_coach': 'مدرب رياضي',
      'nutrition_specialist': 'أخصائي تغذية',
      'other': 'آخر',
      'anxiety_support_group': 'مجموعة دعم القلق',
      'mindfulness_session': 'جلسة اليقظة الذهنية',
      'addiction_recovery': 'التعافي من الإدمان',
      'evening_meditation': 'تأمل مسائي',
      'open_talk': 'حديث مفتوح',
      'dr_sarah': 'د. سارة',
      'coach_mike': 'المدرب مايك',
      'specialist_amine': 'الأخصائي أمين',
      'dr_lina': 'د. لينا',
      'community': 'المجتمع',
      'algeria': 'الجزائر',
      'egypt': 'مصر',
      'saudi_arabia': 'المملكة العربية السعودية',
      'united_states': 'الولايات المتحدة',
      'france': 'فرنسا',
      'rooms': 'غرف',
      'gifts': 'هدايا',
      'profile': 'الملف الشخصي',
      'my_rooms': 'غرفي',
      'now': 'الآن',
      'reserved': 'محجوز',
      'create_room': 'إنشاء غرفة',
      'no_rooms_found': 'لم يتم العثور على غرف',
      'participants': 'مشاركون',
      'active': 'نشط',
      'pending': 'قيد الانتظار',
      'create': 'إنشاء',
      'room_title': 'عنوان الغرفة',
      'enter_room_title': 'أدخل عنوان الغرفة',
      'room_type': 'نوع الغرفة',
      'no_active_rooms': 'لم يتم العثور على غرف نشطة',
      'profile_details': 'تفاصيل الملف الشخصي',
      'coming_soon': 'قريباً',
    },
  };
}
